services:
  postgres:
    image: 'postgres:18.1-alpine'
    container_name: postgres_container
    restart: always
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=secret'
      - 'PGDATA=/var/lib/postgresql/18/data'
    ports:
      - '5432:5432'
    volumes:
      - ./.docker_data/postgres:/var/lib/postgresql/18/data