spring.application.name=demo-reconstitute-factory-model

spring.threads.virtual.enabled=true

spring.sql.init.mode=always

spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

