create table if not exists tb_post (
    post_id char(26) not null,
    status varchar(20) ,
    title varchar(255) not null,
    contents text not null,
    tags varchar(255),
    permanent_link varchar(255),
    created_at timestamp not null,
    created_by varchar(255) not null,
    modified_at timestamp not null,
    modified_by varchar(255) not null,

    constraint pk_tb_post primary key (post_id)
);


create table if not exists tb_comment (
    reply_id bigint generated by default as identity,
    post_id char(26) not null,
    contents text,
    created_at timestamp not null,
    created_by varchar(255) not null,

    constraint pk_tb_comment primary key (reply_id),
    constraint fk_tb_comment_post_id foreign key (post_id) references tb_post(post_id)
);

